apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-svc
spec:
  type: LoadBalancer
  selector:
    app: mongoexpress-app
  ports:
    - name: mongoexpress-port
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30011
