export const languages = ['English', 'Hindi'];

export const languagesTitle = {
    Branch: { "English": "Branch", "Hindi": "शाखा" },
    SignInOrCreateAccount: { 'English': 'Sign in or create account', 'Hindi': "साइन इन करें या खाता बनाएं" },
    SignIn: { 'English': "Sign in", 'Hindi': "साइन इन " },
    SignUp: { 'English': "Sign up", 'Hindi': "साइन अप करें" },
    SignUpType: { "English": "Sign up type", "Hindi": "साइनअप प्रकार" },
    CreateRestaurantAccount: { "English": "Create restaurant account", "Hindi": "रेस्टोरेंट खाता बनाएँ" },
    CreateAccount: { 'English': "Create Account", "Hindi": "खाता बनाएं" },
    YourName: { 'English': "Your name", "Hindi": "आपका नाम" },
    Name: { 'English': "Name", "Hindi": "नाम" },
    atleast: { 'English': "atleast", "Hindi": "कम से कम" },
    characters: { 'English': "characters", "Hindi": "अक्षर" },
    EnterFirstAndLastName: { 'English': "Enter first and last name", 'Hindi': 'प्रथम और अंतिम नाम दर्ज करें' },
    EnterEmail: { 'English': 'Enter email', 'Hindi': "ईमेल दर्ज करें" },
    Email: { 'English': "Email", "Hindi": "ईमेल" },
    Match: { 'English': "match", "Hindi": "इसका मिलान करें" },
    Clear: { 'English': 'clear', 'Hindi': "साफ" },
    ChangePassword: { "English": "Change password", "Hindi": "गुप्त शब्द बदलें" },
    Password: { 'English': "Password", 'Hindi': "गुप्त शब्द " },
    NewPassword: { "English": "New password", "Hindi": "नया गुप्त शब्द" },
    ConfirmPassword: { 'English': "Confirm password", "Hindi": "गुप्त शब्द की पुष्टि करें" },
    Continue: { 'English': "Continue", 'Hindi': 'जारी रखें' },
    ByContinuingYouAgreeToBhojanalya: { 'English': 'By continuing, you agree to Bhojanalya', 'Hindi': 'जारी रखते हुए, आप भोजनालय से सहमत हैं' },
    ConditionsOfUse: { 'English': "Conditions of Use", 'Hindi': 'उपयोग की शर्तें' },
    PrivacyNotice: { 'English': "Privacy Notice", 'Hindi': 'गोपनीयता सूचना' },
    And: { 'English': "and", 'Hindi': 'और' },
    Sale: { 'English': "Sale", 'Hindi': 'बिक्री' },
    Booking: { 'English': "Booking", 'Hindi': 'बुकिंग' },
    InterestBasedAds: { 'English': "Interest-Based Ads", 'Hindi': 'रुचि-आधारित विज्ञापन' },
    Restaurant: { "English": "Restaurant", "Hindi": "रेस्टोरेंट" },
    Id: { "English": "Id", "Hindi": "पहचान" },
    EnterRestaurantId: { 'English': "Enter restaurant id", "Hindi": "रेस्टोरेंट पहचान दर्ज करें" },
    EnterRestaurantName: { 'English': "Enter restaurant id", "Hindi": "रेस्टोरेंट नाम दर्ज करें" },
    EnterBranchName: { 'English': "Enter branch name", "Hindi": "शाखा नाम दर्ज करें" },
    ForgetPassword_CamelCase: { 'English': "Forget password", 'Hindi': " भूल गए गुप्त शब्द" },
    ForgetPassword_SmallCase: { 'English': "forget password?", 'Hindi': " भूल गए गुप्त शब्द?" },

    Options: { 'English': "Options", 'Hindi': 'विकल्प' },
    FastLoading: { 'English': "Fast Loading", 'Hindi': 'फास्ट लोड रखें' },
    Beautify: { 'English': "Beautify", 'Hindi': 'सुंदर' },
    Image: { 'English': "Image", 'Hindi': 'छवि' },
    Thumbnail: { 'English': "Thumbnail", 'Hindi': 'थंबनेल' },
    Theme: { 'English': "Theme", 'Hindi': "दृश्य विषय" },
    Light: { 'English': "Light", 'Hindi': "हल्का" },
    Dark: { 'English': "Dark", 'Hindi': "अँधेरा" },
    ColorBlind: { 'English': "Color-blind", 'Hindi': "वर्णान्ध" },
    Normal: { 'English': "Normal", 'Hindi': "सामान्य" },
    Language: { 'English': "Language", 'Hindi': "भाषा" },
    RestaruantAcccount: { "English": "Restaurant Account", "Hindi": "रेस्टोरेंट खाता" },
    UserAccount: { "English": "User Account", 'Hindi': "उपयोगकर्ता खाता" },
    FontFamily: { 'English': "Font Family", 'Hindi': "फ़ॉन्ट प्रकार" },
    FontSizeVariation: { "English": "Font Size \n Variation", "Hindi": "फ़ॉन्ट आकार \n उतार-चढ़ाव" },
    Show: { "English": "show", 'Hindi': "दिखाओ" },
    Switch: { "English": "switch", 'Hindi': "बदलें" },
    VerifyEmailConsent: { 'English': "To verify your email,\nwe will send you a text message with a temporary code.\nMessage and data rates may apply.", "Hindi": "आपके ईमेल को सत्यापित करने के लिए,\nहम आपको एक अस्थायी कोड के साथ एक टेक्स्ट संदेश भेजेंगे।\nसंदेश और डेटा दरें लागू हो सकती हैं" },
    VerifyEmailAddress: { "English": "Verify email address", "Hindi": "ईमेल पते की पुष्टि करें" },
    OneTimePasswordEmailSend: { "English": "A text with a One Time Password (OTP) has been sent to your email address:", "Hindi": "वन टाइम पासवर्ड (ओटीपी) वाला एक टेक्स्ट आपके ईमेल पते पर भेजा गया है:" },
    EnterOTP: { "English": "Enter OTP :", "Hindi": "ओटीपी दर्ज करें :" },
    CreateYourBhojanalyaAccount: { "English": "Create your Bhojanalya account", "Hindi": "अपना भोजनालय खाता बनाएं" },
    OTP: { 'English': "OTP", "Hindi": "ओटीपी" },
    resendOTP: { "English": "Resent OTP", "Hindi": "पुन: भेजें ओटीपी" }
}