apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-depl
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_url
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            # - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            #   value: test
            # - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            #   value: test_user
            # - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            #   value: test_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-svc
spec:
  type: LoadBalancer
  selector:
    app: mongodb-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
