apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  replicas: 3
  serviceName: mongodb-svc
  selector:
    matchLabels:
      app: mongodb-app
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume
      spec:
        storageClassName: mongodb-sc
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: mongodb-app
        environment: test
    spec:
      containers:
        - name: mongodb-app-container
          image: mongo
          args: ["--dbpath", "/data/db"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume
              mountPath: "/data/db"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
